### ISSUE TITLE
How do I authenticate Yt::Playlist?

### ISSUE THREAD

**Issue by KevinVerre** [claudiob/yt#106]
- I have a playlist ID. It corresponds to a user's playlist of Liked Videos.
- However, when I try to get that Playlist by calling Yt::Playlist.new(id: liked_id), YT says that it did not return any values.
- It shows the URL it is using. Indeed when I put that URL in my browser I don't get any values. I'm getting a Forbidden response.
- But I add &access_token=theAccessTokenString to the URL in my browser I DO get the playlist items in my browser
- So I am not authenticating correctly when I call Yt::Playlist.new(id: liked_id).playlist_items
- I know that I can correctly authenticate using the Yt gem when I am asking for an Account or Channel object. I don't know how to do it with a Playlist.
- I tried Yt::Playlist.new(id: liked_id, access_token: token_string).playlist_items but that didn't work either.
- Please advise.
- **Some background:** If you want to show a user his created playlists you can use Yt::Account.new(access_token: token_string).channel.playlists. However, this does not include the Special Playlists that YouTube has for each User. (liked videos, history of videos watched, uploaded videos, etc.) I couldn't find documentation of how to get these Special Playlists with the Yt Gem. So instead I got the ID for the liked videos playlist querying the YouTube v3 api directly and parsing the response. Now I'm trying to figure out how to use that ID and an authenticated user to get back the playlist.
- The URL I got the id from was something like this: "https://www.googleapis.com/youtube/v3/channels?part=contentDetails&forUsername=#{youtube_username_escaped}&key=#{api_key}&access_token=#{access_token}"
- I might just query YouTube directly again, but it would be simpler if I could use the Gem to do it for me.

**Comment by claudiofullscreen** [comment]
Hello @KevinVerre – I'm sorry, somehow I didn't see this issue before!

The following code works for me, let me know if it solves your issue:

``` ruby
account = Yt::Account.new refresh_token: "1/H..." # or you can use access_token
playlist = Yt::Playlist.new id: "LL...", auth: account # replace with the ID of your 'Liked videos' playlist

playlist.title
# => 'Liked videos'

playlist.playlist_items.count
# => 0
```
