### ISSUE TITLE
Uploading to a video path as in Youtube_it

### ISSUE THREAD

**Issue by thebravoman** [claudiob/yt#107]
Considering a client server scenario where yt is working on the server. 
I don`t want to transfer the whole file to the server, but to have a javascript that uploads it directly from the client.

There is an example for youtube_it - http://www.sitepoint.com/uploading-videos-youtube-rails/
where you upload metadata of the video to youtube from the server and than return a video_path to the client. The client could than send a POST to this url and thus upload the video.

Could this be achieved with yt?

**Comment by stavro** [comment]
Hi @thebravoman,

Unfortunately, through YouTube's latest Data API (V3), this same workflow you describe is unavailable.

However, there are various ways of utilizing OAuth 2.0 access tokens directly in the browser, either by exposing an access token scoped to the particular user to the client's browser, or using a [client-side OAuth workflow](https://developers.google.com/youtube/2.0/developers_guide_protocol_oauth2#OAuth2_Client_Side_Web_Applications_Flow).  By doing this, you could POST a video file directly to YouTube (bypassing your server and the `yt` gem entirely).

If this is still not right, we suggest you express your interest in this feature [directly to the YouTube developer team](https://code.google.com/p/gdata-issues/issues/entry?template=YouTube%20%28Enhancement%20Request%29).

Thanks!

**Comment by thebravoman** [comment]
I have found a way to do it with the resumable uploads and it works very well.

All i need is attr_reader for uri in Resumable Session.

```
 class ResumableSession < Base
   # Sets up a resumable session using the URI returned by YouTube
   +      attr_reader :uri
   +      
```

for this to work. I am still implementing it in our system, but when it is ready I could share it on github.

**Comment by stavro** [comment]
I'd love to see it, certainly!  Exposing the resumable session was not something I had thought of... Would be interesting to see the approach.

**Comment by thebravoman** [comment]
Hi @stavro,

Just for an update:

I have taken another approach and used the Yt::Request directly, because I kind of lost myself in the resumable_session & resumable_sessions.

More on my approach and where I am currently you could check at http://stackoverflow.com/questions/27888158/returned-access-control-allow-origin-is-not-taken-into-account-for-youtube-v3

Hope I could figure this our and contribute as an example.

**Comment by stavro** [comment]
FYI: YouTube added their official stance on the migration from V2 browser uploads to V3:

![image](https://cloud.githubusercontent.com/assets/2391584/5749694/3825a822-9c00-11e4-8bd6-ce0643b7a209.png)

https://developers.google.com/youtube/v3/revision_history

https://developers.google.com/youtube/v3/code_samples/javascript#upload_video
