### ISSUE TITLE
How to authorize for offline access?

### ISSUE THREAD

**Issue by troytc** [claudiob/yt#109]
I'm building my URL using the following code:

```
Yt::Account.new(scopes: ['userinfo.email', 'youtube.readonly'], redirect_uri: new_channel_url).authentication_url
```

Then I use the code like so:

```
yt = Yt::Account.new authorization_code: params[:code], redirect_uri: new_channel_url
```

When accessing `yt.authentication.refresh_token` I get `nil`.  Since the default behavior of the gem requests offline access, shouldn't I be getting a refresh token?

**Comment by stavro** [comment]
Hi @raptblue...  By default, if you are requesting authorization for a user where _that user already has granted offline access to your app_, Google will not give you a duplicate refresh token.  This is probably what you're experiencing.

Try appending `&prompt=consent` to the end of the url and see if it works:

``` ruby
auth_url = Yt::Account.new(scopes: ['...'], redirect_uri: '...').authentication_url + '&prompt=consent'
redirect_to auth_url
```

We are working on getting an official usage of the `prompt` parameter into the gem, but right now it is not included.

**Comment by troytc** [comment]
Sweet.  Works perfectly :)

Thanks!
