### ISSUE TITLE
Support /upload/youtube/v3/thumbnails/set endpoint

### ISSUE THREAD

**Issue by KieranP** [claudiob/yt#111]
Support for setting thumbnail images for videos.

https://developers.google.com/youtube/v3/docs/thumbnails/set

**Comment by KieranP** [comment]
@claudiofullscreen @claudiob We are looking to support uploading thumbnails from our application. I just spent the last hour trying to implement the thumbnails/set endpoint with no success :-( Are you available for contract work to get this piece of functionality implemented for us?

**Comment by claudiofullscreen** [comment]
@KieranP I just managed to do this. Will update Yt soon with the appropriate code.
