### ISSUE TITLE
Article about Yt

### ISSUE THREAD

**Issue by bodrovis** [claudiob/yt#112]
Hi.

Recently I've written an article about this gem (http://www.sitepoint.com/youtube-api-version-3-rails/). Actually this is the second version as the first one was based on youtube_it and gained some positive responses. Maybe you'd want to add this link somewhere.

Thanks for the great gem!

**Comment by stavro** [comment]
Thanks for the article about Yt!

I would also point out that Yt supports all of the oauth mechanisms as well, so there's no need for `google_oauth2` purely for Google Authentication. :)
