### ISSUE TITLE
Performance when requesting additional attributes from search results

### ISSUE THREAD

**Issue by nickcoyne** [claudiob/yt#113]
Due to the limited fields that are returned in search results, yt has to make additional api requests to get some additional fields (specifically we also want duration and view_count). When iterating through a set of search results to do this the performance is poor.

See https://code.google.com/p/gdata-issues/issues/detail?id=4294

Google's suggested workaround is to bundle the additional requests for all search results into a single additional api call. However I don't see a way to do this currently with yt?

**Comment by claudiofullscreen** [comment]
Having you tried with `.where(part: 'statistics,contentDetails')` ?

**Comment by nickcoyne** [comment]
Thanks. So I now collect ids from the first request, and then use those ids in a second request with the part param as above. Pretty sad that we can't do this in one request. And I have to do _another_ request per result to get the channel title :(

**Comment by stavro** [comment]
The Yt::Collection object responds to `.each_slice(50)` which allows you to group results in a more efficient manner:

``` ruby

videos_from_search.each_slice(50) do |yt_video_batch|
  additional_video_parts = Yt::Collections::Videos.new.where id: yt_video_batch.map(&:id).join(','), part: 'statistics,contentDetails'
  #utilize the additional metadata here along with the original video
end
```

You're correct in that it isn't completely seamless interacting with the API in the most efficient way possible, but it is certainly possible.

**Comment by nickcoyne** [comment]
That's helpful, thank you. There isn't any easy way to do pagination, is there?

**Comment by stavro** [comment]
The Yt gem automatically paginates requests when appropriate.  The `#list` endpoint does not support pagination, which is why you need to explicitly group items 50 at a time.

Basic searching through the Yt gem _does_ automatically support pagination.

**Comment by nickcoyne** [comment]
Is there a way to retrieve info for multiple channels in one request? I don't see a collection object for channels? Eg. something that maps to `GET https://www.googleapis.com/youtube/v3/channels?part=snippet&id=UCqOoboPm3uhY_YXhvhmL-WA%2CUCZYTClx2T1of7BRZ86-8fow&key={YOUR_API_KEY}`

**Comment by thewebguy** [comment]
Yeah definitely, check it out:

```
ch = Yt::Collections::Channels.new
channels = ch.where(id: "UCqOoboPm3uhY_YXhvhmL-WA,UCZYTClx2T1of7BRZ86-8fow")
```
