### ISSUE TITLE
While authenticated, can't hit /youtube/v3/videos end point

### ISSUE THREAD

**Issue by KieranP** [claudiob/yt#114]
I'm trying to get all public videos from a channel, then do a /videos call to retrive them and the statistics all at once (since the /search endpoint doesn't support part statistics).

The following doesn't work though, since it always hits /youtube/v3/search...

```
account = Yt::Account.new(....) # properly authenticated
_videos1 = account.channel.videos
puts _videos1.count => 736

ids = _videos1.map(&:id)
_videos2 = ids.in_groups_of(50, false).flat_map { |_ids|
  account.channel.videos.where(
    :id => _ids.join(","),
    :part => "snippet,statistics"
  ).flat_map { |v| v }
}

=> {"error":{"errors":[{"domain":"youtube.part","reason":"unknownPart","message":"statistics","locationType":"parameter","location":"part"}],"code":400,"message":"statistics"}}
```

collections/video.rb#use_list_endpoint looks like it'll only work when doing public requests, since parent is  always set if you go through account.channel.videos...

Any ideas how I can achieve this?

**Comment by claudiofullscreen** [comment]
Mmmh… might be related to #44

**Comment by andrewroth** [comment]
What is the purpose of the @parent check in use_list_endpoint?

**Comment by kangkyu** [comment]
Thank you for using yt gem. We recently opened this "Issues" tab back. We are also working on the prioritization process, to maintain yt better. As a part of maintenance plan, we decided to close all issues from the past, because they might be stale and outdated. Please feel free to reopen if you think necessary.
