### ISSUE TITLE
How to rescue YT::Errors

### ISSUE THREAD

**Issue by zerogee00** [claudiob/yt#124]
I'm getting an error, how do I rescue the error or at least access the exact error message. I am having issues uploading thumbnails and I can't narrow down why it's not working.

Thanks

**Comment by claudiofullscreen** [comment]
Hello @zerogee00 – to rescue Yt::Error simply… `rescue Yt::Error`. For instance:

``` ruby
def your_method_to_upload_thumbnails
  account = Yt::Account.new access_token: 'ya29.1.ABCDEFGHIJ'
  video = Yt::Video.new id: 'MESycYJytkU', auth: account
  video.upload_thumbnail 'http://example.com/remote.png'
rescue Yt::Error => e
  # here you have access to the exception in the variable `e`. 
  # You can use `puts u` or a debugger like `pry` to check what's going on
end
```

Also, remember that if you set the `log_level` to `devel` you will be able to see all the HTTP requests made by Yt, so you can see which request actually failed. To do so, simply add this to your code (anywhere; recommended: in an initializer)

``` ruby
Yt.configure do |config|
  config.log_level = 'devel'
end
```

**Comment by zerogee00** [comment]
Thanks!  The error rescuing is working well, but the thumbnails still won't upload.

```
{"error"=>{"errors"=>[{"domain"=>"youtube.thumbnail", "reason"=>"forbidden",     "message"=>"Forbidden", "locationType"=>"header", "location"=>"Authorization"}], "code"=>403,     "message"=>"Forbidden"}}

A request to YouTube API was considered forbidden by the server
```

But the same account auth was just used in the script to upload a video without error. 

Do I need to refresh the token before attempting to upload the thumbnail?

**Comment by claudiofullscreen** [comment]
No, you don't. But you should do this: go to https://www.youtube.com/features and check that you have the following permission.

![custom-thumbnails](https://cloud.githubusercontent.com/assets/7408595/6679284/e2c13378-cc02-11e4-9669-49c3461ead36.png)

(Maybe I should add that to the guides)

**Comment by zerogee00** [comment]
Thank you! That was the problem. 

Is there any way the gem can return that as the error? 
'You do not have permission to upload thumbnails"

Adding that to the guides would be very helpful too. 

Thanks again.
