### ISSUE TITLE
scopes not passing as parameter

### ISSUE THREAD

**Issue by claudeomusic** [claudiob/yt#126]
tried just doing the very basic thing of initializing an account, with this: (i have @redirect_uri stored in my controller)

```
Yt::Account.new(scopes: 'https://www.googleapis.com/auth/youtube https://www.googleapis.com/auth/userinfo.email https://www.googleapis.com/auth/userinfo.profile' , redirect_uri: @redirect_uri).authentication_url
```

and the response i get was:

Error: invalid_request

Missing required parameter: scope

Request Details
**scope=**
response_type=code
**redirect_uri=http://localhost:3000/youtube/connected** _<- my redirect_uri is getting passed_
access_type=offline
approval_prompt=auto
client_id=820356551033-8iaf7ljkf86m92d3tu202b3b67g4eeg6.apps.googleuserco

**Comment by claudiofullscreen** [comment]
Hello @claudeomusic! 
You don't need the entire URL to specify the scopes. For instance, try this:

``` ruby
Yt::Account.new(scopes: ['youtube', 'userinfo.email', 'userinfo,profile'], redirect_uri: '..your redirect URL..')
```

Does that work? I guess I could improve the documentation with an example :sweat_smile:

**Comment by claudeomusic** [comment]
ahhh ok. yeah i noticed in your documentation you mentioned the shorthand so i tried that first, but i just delimited them by spaces rather than as separate elements in an array (the youtube API specifies space delimited, so i thought maybe you stayed consistent w/that)... thanks a lot for the quick response!
