### ISSUE TITLE
SyntaxError in version 0.14.1

### ISSUE THREAD

**Issue by matuag** [claudiob/yt#132]
**Error message:**

```
SyntaxError: /Users/gautam/.rvm/gems/jruby-1.7.19/gems/yt-0.14.1/lib/yt/collections/reports.rb:6: syntax error, unexpected tLPAREN_ARG
      DIMENSIONS = Hash.new({name: 'day', parse: -> (day) {Date.iso8601 day} }).tap do |hash|
                                                    ^
```

**yt gem version:** 0.14.1

**Ruby version:**
jruby 1.7.19 (1.9.3p551) 2015-01-29 20786bd on Java HotSpot(TM) 64-Bit Server VM 1.8.0_25-b17 +jit [darwin-x86_64]

**Comment by matuag** [comment]
I think the space between -> and (day) (`-> (day)`)  is the cause of syntax error.

http://ruby-journal.com/becareful-with-space-in-lambda-hash-rocket-syntax-between-ruby-1-dot-9-and-2-dot-0/

**Comment by claudiofullscreen** [comment]
Thanks so much for noticing! I don't use jRuby or Ruby 1.9 so I wouldn't have found this bug! :tada:

**Comment by matuag** [comment]
No problem. Glad I could help :-)
