### ISSUE TITLE
Is there a way to automatically eager-load a video on initialization?

### ISSUE THREAD

**Issue by lukevmorris** [claudiob/yt#134]
When a user provides a url to a Youtube video, I'd like to know immediately whether or not that url points to a valid id. As of right now, the gem will accept any url in the initialization phase, and create a video instance:

``` ruby
video = Yt::Video.new(url: "www.facebook.com")
=> #<Yt::Models::Video:0x007fe01dd56240 ...>
```

It's only when I attempt to access data on that video later that an error is thrown:

``` ruby
video.title
=> NameError: uninitialized constant OpenSSL::SSL::SSLErrorWaitReadable
```

Or, for youtube urls with an invalid id:

``` ruby
video = Yt::Video.new(url: "https://www.youtube.com/watch?v=l_JMrETiwQV")
=> #<Yt::Models::Video:0x007fe0168a6530 ...>
video.title
=> Yt::Errors::NoItems: ...
```

Is there any way to configure the gem such that the resource be eager-loaded by default? Here's what I'm doing for the time being to get around the issue:

``` ruby
video = Yt::Video.new(url: "https://www.youtube.com/watch?v=l_JMrETiwQV").tap(&:title)
=> Yt::Errors::NoItems: ...
```

Thanks!

**Comment by stavro** [comment]
Sorry to say, there is currently no support for eager loading.

The process you've outlined is similar to what do we do internally as well in a couple areas.

**Comment by lukevmorris** [comment]
Ok -- the workaround is relatively unobtrusive, so not a big deal. Thanks very much!
