### ISSUE TITLE
Collection mutability issues

### ISSUE THREAD

**Issue by stavro** [claudiob/yt#137]
Unintuitive behavior when attempting to insert a model while iterating through (a separate) collection of that same model.

See the following:

``` ruby
content_owner = Yt::ContentOwner.new '...'
inactive_claims = content_owner.claims.where(asset_id: "A243581141664493", status: "inactive")

inactive_claims.each do |inactive_claim|
  content_owner.create_claim({})
end
```

Even if `inactive_claims.size == 100`, this will only insert one claim.

Upon the first call of `create_claim`, the existing collection (which we're iterating through) is zeroed out and the iteration will terminate.

https://github.com/Fullscreen/yt/blob/master/lib/yt/actions/insert.rb#L14

I feel there should be a way to return an immutable collection when calling `.where`, rather than continuously mutating the same item collection which leads to difficult to debug scenarios like this above.

**Comment by stavro** [comment]
More generally, this affects any nested loops of the same model:

``` ruby
content_owner.claims.where(id: "tso9hpccQxU,gJ4-_ygC5QY,FQLucK0s8SQ").each do |claim_1|
  content_owner.claims.where(id: "JnCeeJXvod4").each {}
  puts claim_1.id
end
#=> tso9hpccQxU
```

You'd expect **three claim_ids** to be printed to the console, but the inner collection stomps over the outer one, and returns completely after the first iteration.

**Comment by claudiofullscreen** [comment]
So, that happens because they are sharing the same internal variables `@items` ? They should use separate variables instead?

**Comment by stavro** [comment]
Every time you type `content_owner.claims.where(...)` you are altering the _same_ memoized collection (see: https://github.com/Fullscreen/yt/blob/master/lib/yt/associations/has_many.rb#L17).

In particular, I don't like this behavior:

``` ruby
content_owner.claims #=> #<Yt::Collections::Claims ...>
content_owner.claims.where(id: "1") #=>  #<Yt::Collections::Claims @where_params={:id=>1} ...>

content_owner.claims #=>  #<Yt::Collections::Claims @where_params={:id=>1} ...>
# I don't like how the @where_params sticks.
```

I think it makes sense to return a new collection each time, rather than persisting the values internally.

My ideal scenario would be to remove the memoization entirely for top-level collections (partnered_channels, assets, references, policies).  If you want to reuse that particular collection object in your application, you should be responsible for keeping a reference to it (similar to how ActiveRecord works - calling `post.comments.where(id: 1)` in one place and then calling `post.comments` again will operate on an two entirely different relation objects).

In terms of memoizing the collection, I would like to see this:

``` ruby
content_owner.claims #=> #<Yt::Collections::Claims ...>
content_owner.where(id: 1) #=> #<Yt::Collections::Claims @where_params={:id=>1} ...>
content_owner.claims #=> #<Yt::Collections::Claims ...>
```

**Comment by claudiofullscreen** [comment]
I think you are talking about #44 :wink:

**Comment by stavro** [comment]
Yep! #44 is also related to unintuitive memoization of the top level collection

**Comment by claudiofullscreen** [comment]
Let's fix #44 and this will probably be fixed too!! :tada:

**Comment by stavro** [comment]
It is more than just the where params though, 'items' and every other instance variable should be reset... So we should just not memoize the collection at all

**Comment by kangkyu** [comment]
Thank you for using yt gem. We recently opened this "Issues" tab back. We are also working on the prioritization process, to maintain yt better. As a part of maintenance plan, we decided to close all issues from the past, because they might be stale and outdated. Please feel free to reopen if you think necessary.
