### ISSUE TITLE
Yt::Collections::Videos returns same video more than once

### ISSUE THREAD

**Issue by tomfbiz** [claudiob/yt#139]
For instance when I do the following query:

``` ruby
    items = Yt::Collections::Videos.new.where(q:"greens of london", safe_search: 'strict',embeddable: true)
```

items.count returns 199
...but if I do items.first(80)
i[0].id==i[22].id and i[37].id and i[52] and i[74]

and similarly i[1]==[i[23] and 38,53,75

But if I change the search term to "Justin" I get all unique results.

If I search for "Freudenheim" I get 4 results, but the first is the same as the third and the 2nd is the same as the 4th.

**Comment by stavro** [comment]
Thanks @tomfbiz 

This unfortunately is exactly how the API works itself.  The `Yt` gem doesn't do any de-duplication internally.  We'd rather you implement this logic inside your application to handle it how you want to.

I confirmed that it works exactly as the API responds with the query _Freudenheim_.

You can confirm this yourself by going to the [Google API Explorer](https://developers.google.com/youtube/v3/docs/search/list) and entering the same parameters (`Yt` does however add in a default sort of `date`, which I would like to change).

**Comment by tomfbiz** [comment]
You are correct, the issue does seem to be related to that default date search.

When searching without  sort order in the API Explorer, I get 5 per page, and the paginations works when searching for Freudenheim, but when I add the order:date, I only get 2 items per page, and several pages that are identical (and order by viewcount gives me the exact same glitchty result).

I would recommend that you remove the default sort, and use google's default of relevance. 

I am removing duplicates on my own, but I only get 2 results for Freudenheim, when there should be getting 208 results.

**Comment by stavro** [comment]
@tomfbiz  Thanks!  For now, you can get proper search results by adding `sort: 'relevance'` yourself, correct?

**Comment by tomfbiz** [comment]
@stavro 

No, I tried that. It seems that the gem is ignoring that parameter. My searches for "Freudenheim" and for "ballet" return the same results regardless of that param. Is there a way to see the api calls that the gem is sending and receiving? 

Here is what I'm trying:

v=videos.where(q: 'Freudenheim', safe_search: 'none',sort:'relevance').first(10)

Thanks for your prompt responses.

**Comment by tomfbiz** [comment]
@stavro

I will open a new but that the sort:'relevance' doesn't work.

I was forced to go live with the bad search results, since Youtube is disabling the v2 apis.

**Comment by tomfbiz** [comment]
I figured out that using order:'relevance'  rather than sort:   fixed the problem.
