### ISSUE TITLE
Missing video attributes that youtube_it provides

### ISSUE THREAD

**Issue by subimage** [claudiob/yt#149]
youtube_it user here, looking to possibly migrate since it looks as if they won't be supporting the v3 API.

However, I'm missing some major things on the 'video' resource, such as:
- embed_html_with_width (returns html embed code)
- player_url (returns URL of video)

I'm poking around the video model and don't see a way to access any of this. A little help? Thanks!

**Comment by subimage** [comment]
Looks like I can construct the player_url easily enough, but what about returning 'embedHtml' from the 'player' resource?

**Comment by claudiofullscreen** [comment]
Hello @subimage and welcome! 

Could you point me to where those methods are defined in the [YouTube API V3 Docs](https://developers.google.com/youtube/v3/)? I can take a look and see if they can be easily ported to Yt

**Comment by subimage** [comment]
player_url seems like it can be constructed from the unique Youtube ID, so that's not a big deal.

embed_html looks as if it's returned from the API here as player['embedHtml']

https://developers.google.com/youtube/v3/docs/videos

I don't see a height/width param for it, so I'm guessing youtube_it adds both of those as convenience methods.

**Comment by claudiofullscreen** [comment]
@subimage If you update the Yt gem to 0.15.2, you should be able to get it now:

``` ruby
Yt.configuration.api_key = "<YOUR API KEY>"

video = Yt::Video.new id: "<any video ID>"
video.embed_html
# =>  "<iframe type='text/html' src='http://www.youtube.com/embed/<ID>' width='640' height='360' frameborder='0' allowfullscreen='true'/>"

```

**Comment by subimage** [comment]
Thanks!

**Comment by benmagrey** [comment]
Hi, I know this issue is closed, but I couldn't find more info about this. Is there any possibility to configure the width and height in the embed code that's generated by the gem?
