### ISSUE TITLE
Plan to release 1.0

### ISSUE THREAD

**Issue by claudiofullscreen** [claudiob/yt#156]
As this project turns one year, and as YouTube is deprecating V2, it’s time to make some decisions about the API of Yt and clarify which objects and methods are available.

I feel pretty confident about the current classes and methods of Yt. I don't intend to replace something as simple as: `video = Yt::Video.new id: 'video_id'; video.title` with anything else. I just want to make sure that every public method is documented, before I can say **this** is version 1.0 of Yt.

So far, I have fully documented two classes. Here are the [API documentation](http://www.rubydoc.info/gems/yt/Yt/Models/Video) and [usage guide](http://fullscreen.github.io/yt/videos.html) for `Yt::Video`, and here are the [API documentation](http://www.rubydoc.info/gems/yt/Yt/Models/Channel) and [usage guide](http://fullscreen.github.io/yt/channels.html) for `Yt:Channel`.

In the next days I'll be working on the remaining classes. If you have any feedback on methods that should **be deprecated** or that should **have a different signature**, this is the right time to reach out.

To clarify, v1.0 does not mean that new features won't be added. It just guarantees that all the public classes and methods available in v1.0 won't get changed until v2.0.

If you scroll through the [CHANGELOG](https://github.com/Fullscreen/yt/blob/master/CHANGELOG.md) you can get an idea of methods that have been in Yt at some moments and won't be part of 1.0.

Thanks for your support and feedback! @stavro @KieranP @subimage @tomfbiz @lukevmorris @matuag @claudeomusic @zerogee00 @NARKOZ @nickcoyne @bodrovis @raptblue @thebravoman @KevinVerre @hakunin @Grafikart @Catchouli @sbounmy @datnt @kxcrl @dustinleblanc @jdwolk @timzero @pwnall

**Comment by bodrovis** [comment]
This is great and thank you for letting us know! I will definetely think of it as I am quite extensively using YT API for various widgets.

**Comment by subimage** [comment]
One thing that doesn't make sense to me is that the "create_playlist" method is on Yt::Account, but all the other playlist operations happen on Yt::Channel.

How do I create a playlist on a certain channel?

**Comment by subimage** [comment]
Also - maybe it's just a rails thing...but to me doing something like this:

``` ruby
Yt::Playlist.new id:  'PLSWYkYzOrPMRUYaLE6C9'
```

Makes me think I'm "creating" a playlist. I think using `find` might be a more easy to understand paradigm. The whole method signature seems a bit off, and could use some redesign I think.

I understand all the operations closely mirror the YouTube API, but if we're following "the ruby way" here, I think a lot could be done to improve design and interface of the entire gem.

**Comment by subimage** [comment]
Leaving these as I work through a project with the gem. Sorry to overwhelm.

Another oddity...

``` ruby
playlist.add_video "BPNYv0vd78A" # => #<Yt::PlaylistItem …>
playlist.add_videos %w{BPNYv0vd78A 2NW_AqhkYZZ} # => [#<Yt::PlaylistItem …>]
playlist.delete_playlist_items video_id: "BPNYv0vd78A" # => [true, false]
```

Why is it `add_video`, but `delete_playlist_items`, and `playlist_items`, instead of `remove_video` and `videos`

Lots of little inconsistencies in the design of the gem, which I was referencing in my previous message.

**Comment by claudiofullscreen** [comment]
@subimage Thanks for your feedback. 

Regarding those `playlist` methods, are you suggesting to add a method

``` ruby
playlist.remove_video "BPNYv0vd78A"
```

equivalent to

``` ruby
playlist.delete_playlist_items video_id: "BPNYv0vd78A"
```

to delete all items of the playlist that reference a specific video?

**Comment by claudiofullscreen** [comment]
> I understand all the operations closely mirror the YouTube API, but if we're following "the ruby way" here, I think a lot could be done to improve design and interface of the entire gem.

This is why I opened this discussion :ribbon: What specific design issue would you change and how?

---

> Makes me think I'm "creating" a playlist. I think using find might be a more easy to understand paradigm. The whole method signature seems a bit off, and could use some redesign I think.

I think there is a little confusion here. 
If there ever was an ActiveRecord-inspired `find` method, then I would expect that method to actually go and _fetch_ the thing you want to find. In other words, I would expect something like:

``` ruby
Yt::Playlist.find 'PLSWYkYzOrPMRUYaLE6C9'
```

to actually establish an HTTP connection to YouTube and "find" (that is, fetch, retrieve) that playlist object.

That is **not** what `Yt::Playlist.new id: 'PLSWYkYzOrPMRUYaLE6C9'` does or it's supposed to do.
Calling `new` is the _Ruby way_ to initialize a Ruby object with some attributes, so here we are initializing a `Yt::Playlist` object with an `id` parameter. We could initialize it with a `url`, or with other attributes, but that's all `.new` does: instantiate an object. It's not supposed to make any HTTP connection.

**Comment by subimage** [comment]
I think making the distinction between "initializing" and "finding and fetching" is a bit weird.

As a user of the library, I just want the thing. I don't want to think about the technical details of it. I understand you're mirroring the API 1:1 with the gem, but it makes it weird to think about for us, and more difficult to use than it should be.

For me, when I write an API client, I try to design it in such a way that it abstracts those ugly bits away from the API consumer. Personal preference, perhaps...but I think it creates a better overall experience.

Perfect example - is the `delete_playlist_items` vs `remove_video` issue I referenced above. I understand that the YouTube API has 'playlist items', but for my uses, I just want to access videos, add/remove them from lists.

If you have an "add_video" method, you should have the reverse operation, named similarly. I had to go into the YouTube API reference to figure out what the heck "playlist_items" are. Again, as a gem consumer I really don't want to think about that stuff.

Just my $0.02, but thanks again for the library and starting this discussion to improve it! I know it's difficult and time consuming to maintain open source projects like these.

**Comment by subimage** [comment]
This is probably a youtube API specific issue as well, but doing this gives me a permission error:

``` ruby
$yt_acct = Yt::Account.new(
  refresh_token: Settings.youtube.web_app.refresh_token
)
puts $yt_acct.playlists.first.inspect
```

Where this works...

``` ruby
$yt_acct = Yt::Account.new(
  refresh_token: Settings.youtube.web_app.refresh_token
)
puts $yt_acct.channel.playlists.first.inspect
```

I feel that at every point I'm having to think about how the API is designed, rather than just using an interface to Youtube. Hope that makes sense.

**Comment by aharpole** [comment]
@subimage The constructors can be a bit weird at first, especially if you use Rails and you're use to how ActiveRecord gives you objects that are tightly coupled to the database record beneath it.

Think of it like this: when you say `Yt::Video.new` you aren't creating a new YouTube video, you're creating a `Yt::Video` object. The `Yt::Video` object is somewhat decoupled from actually communicating with YouTube; it's just a plain old Ruby object.  This decoupling is good practice on bigger projects, even if it is a bit less convenient up front. 

One area where using a normal constructor (as opposed to a `find` constructor): you don't send a request over the wire until you absolutely need to. If we consumed an API call just for instantiating an object, that could add up to a lot of useless requests to YouTube.

**Comment by subimage** [comment]
@aharpole totally understand that. I've been writing Ruby since 2006.

Maybe I haven't been using the gem long enough, but in what cases do you just need the object without communicating with YouTube? Why would you want to instantiate a Video object with an ID? AFAIK you can't really _do_ anything with that object without talking to YouTube somewhere down the line.

**Comment by claudiofullscreen** [comment]
@subimage:
1. the `account.playlists` behavior is definitely a bug and I will deal with that separately
2. I don't disagree with adding `playlist.remove_video "BPNYv0vd78A"`
3. I will still keep `playlist.delete_playlist_items`, because deleting playlist items _by video ID_ is just a sub-case of this. With `delete_playlist_items` you can delete items by (total or partial) matching of their title, description, etc.
4. I instantiate a Video object because then I can lazy load the attributes that I need when I need. If I had the eager-load the entire Video object from YouTube API, then I would probably have to ask upfront for its snippet, statistics, analytics, content details etc. That would take time and use YouTube API quota. Instead, each thing is requested when you need it (for instance `video.title` loads snippet, while `video.estimated_minutes_watched` loads analytics), and simply calling `new` does not take time

**Comment by claudiofullscreen** [comment]
@subimage Thanks for reporting the bug about `account.playlists`. It should work now, just update your gem to `0.21.0`

**Comment by subimage** [comment]
> the account.playlists behavior is definitely a bug and I will deal with that separately
> I don't disagree with adding playlist.remove_video "BPNYv0vd78A"

Thank you for listening & fixing!

> I will still keep playlist.delete_playlist_items, because deleting playlist items by video ID is just a sub-case of this. With delete_playlist_items you can delete items by (total or partial) matching of their title, description, etc.

Of course, totally understood.
