### ISSUE TITLE
Support for captions https://developers.google.com/youtube/v3/docs/captions

### ISSUE THREAD

**Issue by rojesh** [claudiob/yt#164]

**Comment by claudiofullscreen** [comment]
Hello @rojesh and thanks for stopping by!

Are you planning on adding code to Yt to support captions? :wink: 
We need everyone’s support to ensure Yt covers the entire YouTube API

**Comment by nickcoyne** [comment]
Hi, any progress on adding caption support?

**Comment by nickcoyne** [comment]
Or pointers on a good base from which to start so that I can add it?
