### ISSUE TITLE
SystemStackError: stack level too deep on to_json

### ISSUE THREAD

**Issue by pikitgb** [claudiob/yt#166]
Hi i'm getting this error when I try to convert the response from Yt::Channel to json.

``` ruby
Yt.configure do |config|
  config.api_key = "mykey"
end

chann = Yt::Channel.new id: "UCWI70VlhoBiCvhmDMQle9UA"
chann.to_json
```

Show this output:

SystemStackError: stack level too deep
        from /home/mbeach/.rvm/gems/ruby-2.2.0@merge6/gems/activesupport-4.2.0/lib/active_support/core_ext/object/instance_variables.rb:13:in `instance_values'
        from /home/mbeach/.rvm/gems/ruby-2.2.0@merge6/gems/activesupport-4.2.0/lib/active_support/core_ext/object/json.rb:50:in`as_json'
        from /home/mbeach/.rvm/gems/ruby-2.2.0@merge6/gems/activesupport-4.2.0/lib/active_support/core_ext/object/json.rb:159:in `block in as_json'
        from /home/mbeach/.rvm/gems/ruby-2.2.0@merge6/gems/activesupport-4.2.0/lib/active_support/core_ext/object/json.rb:159:in`each'
        from /home/mbeach/.rvm/gems/ruby-2.2.0@merge6/gems/activesupport-4.2.0/lib/active_support/core_ext/object/json.rb:159:in `map'
        from /home/mbeach/.rvm/gems/ruby-2.2.0@merge6/gems/activesupport-4.2.0/lib/active_support/core_ext/object/json.rb:159:in`as_json'
        from /home/mbeach/.rvm/gems/ruby-2.2.0@merge6/gems/activesupport-4.2.0/lib/active_support/core_ext/object/json.rb:50:in `as_json'
        from /home/mbeach/.rvm/gems/ruby-2.2.0@merge6/gems/activesupport-4.2.0/lib/active_support/core_ext/object/json.rb:159:in`block in as_json'
        from /home/mbeach/.rvm/gems/ruby-2.2.0@merge6/gems/activesupport-4.2.0/lib/active_support/core_ext/object/json.rb:159:in `each'
        from /home/mbeach/.rvm/gems/ruby-2.2.0@merge6/gems/activesupport-4.2.0/lib/active_support/core_ext/object/json.rb:159:in`map'
        from /home/mbeach/.rvm/gems/ruby-2.2.0@merge6/gems/activesupport-4.2.0/lib/active_support/core_ext/object/json.rb:159:in `as_json'
        from /home/mbeach/.rvm/gems/ruby-2.2.0@merge6/gems/activesupport-4.2.0/lib/active_support/core_ext/object/json.rb:50:in`as_json'
        from /home/mbeach/.rvm/gems/ruby-2.2.0@merge6/gems/activesupport-4.2.0/lib/active_support/core_ext/object/json.rb:159:in `block in as_json'
        from /home/mbeach/.rvm/gems/ruby-2.2.0@merge6/gems/activesupport-4.2.0/lib/active_support/core_ext/object/json.rb:159:in`each'
        from /home/mbeach/.rvm/gems/ruby-2.2.0@merge6/gems/activesupport-4.2.0/lib/active_support/core_ext/object/json.rb:159:in `map'
        from /home/mbeach/.rvm/gems/ruby-2.2.0@merge6/gems/activesupport-4.2.0/lib/active_support/core_ext/object/json.rb:159:in`as_json'
... 7851 levels...
        from /home/mbeach/.rvm/gems/ruby-2.2.0@merge6/gems/activesupport-4.2.0/lib/active_support/core_ext/object/json.rb:159:in `block in as_json'
        from /home/mbeach/.rvm/gems/ruby-2.2.0@merge6/gems/activesupport-4.2.0/lib/active_support/core_ext/object/json.rb:159:in`each'
        from /home/mbeach/.rvm/gems/ruby-2.2.0@merge6/gems/activesupport-4.2.0/lib/active_support/core_ext/object/json.rb:159:in `map'
        from /home/mbeach/.rvm/gems/ruby-2.2.0@merge6/gems/activesupport-4.2.0/lib/active_support/core_ext/object/json.rb:159:in`as_json'
        from /home/mbeach/.rvm/gems/ruby-2.2.0@merge6/gems/activesupport-4.2.0/lib/active_support/core_ext/object/json.rb:50:in `as_json'
        from /home/mbeach/.rvm/gems/ruby-2.2.0@merge6/gems/activesupport-4.2.0/lib/active_support/json/encoding.rb:34:in`encode'
        from /home/mbeach/.rvm/gems/ruby-2.2.0@merge6/gems/activesupport-4.2.0/lib/active_support/json/encoding.rb:21:in `encode'
        from /home/mbeach/.rvm/gems/ruby-2.2.0@merge6/gems/activesupport-4.2.0/lib/active_support/core_ext/object/json.rb:37:in`to_json_with_active_support_encoder'
        from (irb):66
        from /home/mbeach/.rvm/gems/ruby-2.2.0@merge6/gems/railties-4.2.0/lib/rails/commands/console.rb:110:in `start'
        from /home/mbeach/.rvm/gems/ruby-2.2.0@merge6/gems/railties-4.2.0/lib/rails/commands/console.rb:9:in`start'
        from /home/mbeach/.rvm/gems/ruby-2.2.0@merge6/gems/railties-4.2.0/lib/rails/commands/commands_tasks.rb:68:in `console'
        from /home/mbeach/.rvm/gems/ruby-2.2.0@merge6/gems/railties-4.2.0/lib/rails/commands/commands_tasks.rb:39:in`run_command!'
        from /home/mbeach/.rvm/gems/ruby-2.2.0@merge6/gems/railties-4.2.0/lib/rails/commands.rb:17:in `<top (required)>'
        from bin/rails:4:in`require'

What should I do to get the json correctly ?

**Comment by claudiofullscreen** [comment]
@pikitgb You are right, I get the same error, and that happens because I didn't think of implementing a `to_json` methods on the Yt models.

Can you explain me what is the data you are trying to extract in a JSON format?
A channel can have a lot of information coming from different endpoints: snippet, analytics, content.
Are you looking for something specific?

**Comment by claudiofullscreen** [comment]
For instance, if what you are looking for is the "snippet" information of that channel (title, description etc), you can write the following:

``` ruby
require 'yt'
chann = Yt::Channel.new id: "UCWI70VlhoBiCvhmDMQle9UA"
chann.snippet.data
# => {"title"=>"Vicente Fuentes", 
# "description"=>"Este es un canal de misterios, conspiraciones, avistamientos de OVNIS y opinión realizado con cariño por el ingeniero, profesor, escritor e investigador Vicente Fuentes. \n\nMás información en su página web: http://www.ufopolis.com\n\nEsperamos que todos los contenidos sean de su agrado.", 
# "publishedAt"=>"2010-11-15T21:49:09.000Z", 
# "thumbnails"=>{"default"=>{"url"=>"https://yt3.ggpht.com/-kW2fsTl0oG4/AAAAAAAAAAI/AAAAAAAAAAA/fX9HStSBYsw/s88-c-k-no/photo.jpg"}, "medium"=>{"url"=>"https://yt3.ggpht.com/-kW2fsTl0oG4/AAAAAAAAAAI/AAAAAAAAAAA/fX9HStSBYsw/s240-c-k-no/photo.jpg"}, "high"=>{"url"=>"https://yt3.ggpht.com/-kW2fsTl0oG4/AAAAAAAAAAI/AAAAAAAAAAA/fX9HStSBYsw/s240-c-k-no/photo.jpg"}}, 
# "localized"=>{"title"=>"Vicente Fuentes", "description"=>"Este es un canal de misterios, conspiraciones, avistamientos de OVNIS y opinión realizado con cariño por el ingeniero, profesor, escritor e investigador Vicente Fuentes. \n\nMás información en su página web: http://www.ufopolis.com\n\nEsperamos que todos los contenidos sean de su agrado."}}
```

which is simply the Hash of data returned by YouTube API, on which you can call `.to_json`.
