### ISSUE TITLE
Is there any age restriction for the video

### ISSUE THREAD

**Issue by praneeththota** [claudiob/yt#173]
Is there any method to know age restriction for the video. I tried like this
video = Yt::Video.new url: 'https://www.youtube.com/watch?v=p5Lj3y3mOxw'
video.annotation.above? 50
error: NoMethodError: undefined method `annotation' for #Yt::Models::Video:0x007f30d62b34b0

video.annotations.above? 50
error: NoMethodError: undefined method `annotation' for #Yt::Models::Video:0x007f30d62b34b0

**Comment by praneeththota** [comment]
I heard that YouTube API V3 does not provide access to video annotations, therefore a legacy XML endpoint is used to retrieve annotations.
How to get the XML endpoint to retrieve annotations in rails ?

**Comment by claudiofullscreen** [comment]
Hello @praneeththota.

Regarding the error you get, there is no `.annotation` (singular) method on `Yt::Video`; instead there is a plural `.annotations` method that returns all the annotations [as documented here](http://fullscreen.github.io/yt/annotations.html)

Therefore you could write `video.annotations.first.above? 50` to know if the first annotation of the video is in the top half of the video frame.

However, that is not related to "age restriction". I looked at the YouTube API V3 documentation and this is what I found:

![screen shot 2015-05-15 at 7 12 03 am](https://cloud.githubusercontent.com/assets/7408595/7654414/be5b1230-fad1-11e4-9c79-1cca5c6af9c2.png)

If this is what you are looking for, it's not implemented in Yt… but pull requests are welcome!

**Comment by jacknguyen** [comment]
@praneeththota like @claudiob said there is no single method to check for content rating of a video but you can do so by checking the content_detail of the video and parsing down until you find the contentRating.

What I was able to do:
`video.content_detail.data['contentRating']`

Youtube can send back a number of possible values back which is [documented here](https://developers.google.com/youtube/v3/docs/videos) under `contentDetails.contentRating`. But I think the most common one might just be `ytRating` which only has only one possible return value `ytAgeRestricted`.

**Comment by praneeththota** [comment]
Yeah exactly i'm searching for this. Thanks alot @jacknguyen , @claudiofullscreen
