### ISSUE TITLE
channel.videos is missing a couple results

### ISSUE THREAD

**Issue by mrhaddad** [claudiob/yt#179]
Hi, I have a channel with 30 public videos, but only 28 are returned via:

```
channel = Yt::Channel.new id: 'UCu6xSm33KXu8F2vo7UkzYsQ'
videos = channel.videos.includes(:statistics)
```

Thoughts? I assume this is a problem with the YouTube API as opposed to yt, but thought I'd ask here first.

**Comment by claudiofullscreen** [comment]
@mrhaddad First of all… I love your videos! :musical_keyboard: 

You are right, looking at your YouTube channel page, I can see that two videos are missing:
- JS Bach, Partita No. 2 in C minor
- Les Misérables, Castle on a Cloud

However… that's what the YouTube API returns, and I don't know why. You can try to access the YouTube API directly with the following code, and you will see that the videos are not there :cry::

```
curl -X GET -H "content-length: 0" -H "user-agent: Yt::Request (gzip)" "https://www.googleapis.com/youtube/v3/search?channelId=UCu6xSm33KXu8F2vo7UkzYsQ&key=<YOUR API KEY>&maxResults=50&order=date&part=snippet&type=video"
```

Interesting enough, if you try to access those videos through the API, they can be accessed, and their channel ID matches your channel.

So… I don't know how to help, looks like it's a YouTube bug that I haven't seen before.
Maybe it's a caching issue… try again in a couple of days and see if it's resolved.

**Comment by mrhaddad** [comment]
Yeah, I tried accessing the two videos directly to see if anything was different about them, but it appears they are the same. Thanks for your help and a functional gem for the new API! See the gem (minus the aforementioned videos) in action at http://bootynonstop.com.

**Comment by mrhaddad** [comment]
Still not working, although it does return all 31 videos (I added one) if I query by the playlist for my channel's uploaded videos.

```
playlist = Yt::Playlist.new id: 'UUu6xSm33KXu8F2vo7UkzYsQ'
videos = playlist.playlist_items.map(&:video)
```

Only problem with this is there does not appear to be a way to eager load the view counts (e.g., includes(:statistics)). Is that right?

**Comment by mrhaddad** [comment]
Oh cool, spontaneous resolution!
