### ISSUE TITLE
Search is way too slow

### ISSUE THREAD

**Issue by khanimdad** [claudiob/yt#184]
I have flowing code...
 client = Yt::Collections::Videos.new
 videos = client.where(q: keyword, safe_search: 'none',order: 'viewCount',maxResults: 20)

When processing videos i end up to process all results which is too slow (because of so many results) so how can i limit it to n records only?

**Comment by claudiofullscreen** [comment]
If you only want to process the (say) title of the first (say) 60 videos, you can follow the code above with:

```ruby
videos.first(60).map{|x| x.title}
```

In general, the list of results is an Enumerator, so you can use [any of these methods](https://github.com/Fullscreen/yt/blob/master/lib/yt/actions/list.rb#L9L10):

```ruby
:any?, :count, :each, :each_cons, :each_slice, :find, :first, :flat_map, :map, :size
```

**Comment by claudiofullscreen** [comment]
@khanimdad 
If you only want to process the (say) title of the first (say) 60 videos, you can follow the code above with:

``` ruby
videos.first(60).map{|x| x.title}
```

In general, the list of results is an Enumerator, so you can use [any of these methods](https://github.com/Fullscreen/yt/blob/master/lib/yt/actions/list.rb#L9L10):

``` ruby
:any?, :count, :each, :each_cons, :each_slice, :find, :first, :flat_map, :map, :size
```

**Comment by sheharyarn** [comment]
Suppose, I'd like to paginate and show 10 videos per page. How would I fetch the next 10 videos for the second page, and then, the next 10 videos for the third page and so on?

**Comment by kangkyu** [comment]
Thank you for using yt gem. We recently opened this "Issues" tab back. We are also working on the prioritization process, to maintain yt better. As a part of maintenance plan, we decided to close all issues from the past, because they might be stale and outdated. Please feel free to reopen if you think necessary.
