### ISSUE TITLE
Batch video lookup

### ISSUE THREAD

**Issue by catchouli** [claudiob/yt#186]
Thanks for this software. I'm using 0.24.0.

I'm trying to look up a list of videos and display them on a page, but recently it got very slow. I installed rack-mini-profiler to check what was going on. Here's my code:

``` ruby
videoData = Yt::Collections::Videos.new.where(id: "UL6PN8qVtVU,iCWhr6ANr7U,kOUv7jL4dhc,WNKp8E-Hqg0,YmFPrfDvXL8,UycF9NrvWyE,Awm4C1ghW4s,6fC4E7mm5z4")

@recent = videoData.map { |v| { video_id: v.id,
                                title: v.title,
                                views: v.view_count,
                                duration: v.duration } }
```

The problem is that it not only seems to do one look up per video, but multiple. Here's the output of rack-mini-profiler: https://dl.dropboxusercontent.com/u/95554481/pictures/yt.PNG

Apologies if it's my sample that's the problem.

Cat

**Comment by claudiofullscreen** [comment]
@Catchouli Trying adding the `part` parameter to your `where` condition, to instruct `Yt` to retrieve specific parts of the video.

In the example above, you can change your code to:

``` ruby
videoData = Yt::Collections::Videos.new.where(part: 'snippet,statistics,contentDetails', id: "UL6PN8qVtVU,iCWhr6ANr7U,kOUv7jL4dhc,WNKp8E-Hqg0,YmFPrfDvXL8,UycF9NrvWyE,Awm4C1ghW4s,6fC4E7mm5z4")
@recent = videoData.map { |v| { video_id: v.id, title: v.title, views: v.view_count,  duration: v.duration } }
```

and Yt will only run a single HTTP request:

```
curl -X GET -H "content-length: 0" -H "user-agent: Yt::Request (gzip)" "https://www.googleapis.com/youtube/v3/videos?id=UL6PN8qVtVU%2CiCWhr6ANr7U%2CkOUv7jL4dhc%2CWNKp8E-Hqg0%2CYmFPrfDvXL8%2CUycF9NrvWyE%2CAwm4C1ghW4s%2C6fC4E7mm5z4&key=<KEY>&maxResults=50&order=date&part=snippet%2Cstatistics%2CcontentDetails&type=video"
```

**Comment by catchouli** [comment]
@claudiofullscreen

Ooh is that how it works? Sorry, I'm not familiar with the vanilla API. That works perfectly, thanks for your response.

One more thing, do you know if this is possible to do for a channel's videos? For example, to look up the 8th most viewed videos i'm doing:

``` ruby
ch = Yt::Channel.new url: 'youtube.com/raocow'
@popular = ch.videos.where(order: 'viewCount', part: 'snippet', maxResults: 8)
```

It seems the only part value available for searches is snippet, so maybe it's intended that you do this kind of query in two parts.

Otherwise, this can be closed. Thank you!

**Comment by claudiofullscreen** [comment]
@Catchouli This is how you would do it for the videos of a channel:

``` ruby
ch = Yt::Channel.new url: 'youtube.com/raocow'
ch.videos.where(order: 'viewCount').includes(:statistics).first(8).map{|v| v.view_count}
```

In short, use `.includes` after your `where` statement.

**Comment by catchouli** [comment]
@claudiofullscreen Oh right, so there is a way. Thanks again.

**Comment by emmx** [comment]
Any way to do the same with playlists? I just opened a new issue.
