### ISSUE TITLE
308 Resume Incomplete

### ISSUE THREAD

**Issue by jayhuber** [claudiob/yt#192]
In the past day, I have had a few videos go to a 308 Resume Incomplete when uploading.  If I attempt the upload again, I then get that the video is a duplicate, because it actually made it up the first time - with the below exception.  What I am not getting back when the exception is happening is the ID assigned to the upload.  If I had the ID I could check on the video to see if it completed - I need this ID for my app so I can react to it.

If I upload the same video a second time, YouTube says it is duplicate, but I don't see any information about the video that it matches in its response.  Either way, I am seeking the ID of the first video.

Is it possible to turn off resumable?  Thoughts about this error?  

```
{"request_curl":"curl -X PUT -H \"transfer-encoding: chunked\" -H \"x-upload-content-length: 42066390\" -H \"x-upload-content-type: video/*\" -H \"user-agent: Yt::Request (gzip)\" -H \"authorization: Bearer xxxxxxxxxxxx\" -H \"host: www.googleapis.com\" -H \"content-type: application/x-www-form-urlencoded\" \"https://www.googleapis.com/upload/youtube/v3/videos?part=snippet%2Cstatus\u0026uploadType=resumable\u0026upload_id=AEnB2Uq5iicvetrvHJ-3xQ2jzubwVZjvUi0tIWDz5TDrOinya_mQZATQA5uZkKxRG6z7qfZmPv5SnoHNfMhIXTd4Ola5XKk1dw\"","response_body":"#\u003cNet::HTTPRedirection 308 Resume Incomplete readbody=true\u003e"}  
```

Appreciate any help.

**Comment by kangkyu** [comment]
Thank you for using yt gem. We recently opened this "Issues" tab back. We are also working on the prioritization process, to maintain yt better. As a part of maintenance plan, we decided to close all issues from the past, because they might be stale and outdated. Please feel free to reopen if you think necessary.
