### ISSUE TITLE
Implement support for large video file uploads without massive memory consumption

### ISSUE THREAD

**Issue by KieranP** [claudiob/yt#20]
As per comment on: 2d68bdbd83308a936efaf22d6ede5f6c6906073d

Looks like the current implementation reads the whole file into memory, then sends to YouTube. This will be crippling for video files several GB in size.

youtube_it handles this nicely by downloading and saving a chunk of the file at a time, then on upload, sending a chunk of the file at a time. See these two files for inspiration:

Downloading: https://github.com/kylejginavan/youtube_it/blob/master/lib/youtube_it/request/remote_file.rb
Uploading: https://github.com/kylejginavan/youtube_it/blob/master/lib/youtube_it/chain_io.rb

**Comment by claudiofullscreen** [comment]
@KieranP You’re completely right! I just added the video/upload feature and I started from the easiest case: a file uploaded in its entirety to YouTube. I know YouTube API accepts [Resumable Uploads](https://developers.google.com/youtube/v3/guides/using_resumable_upload_protocol#Start_Resumable_Session) and I'm looking into that now. I'll keep you updated.

**Comment by claudiofullscreen** [comment]
@KieranP – I have a question for you.

I'm trying to optimize the upload process and my first step (#25) has been to use `Transfer-Encoding: chunked`, so the file is sent one chunk at the time.

My next step is to make sure that, if I upload a file that occupies 45MB, the RAM used by the Ruby process does not increase of 45MB. 

I expected this to be the case for `youtube_it`, but instead (according to my benchmarks below), `youtube_it` as well increases the memory size by ~45MB when uploading such a file.

Am I missing something? Am I looking in the wrong direction?

``` ruby
require 'youtube_it'
client = YouTubeIt::OAuth2Client.new(client_access_token: "ya29.RQB2....")

# The file being uploaded is 45MB
video_path = "/movies/example.mov"
File.size video_path #=> 45805560

# Before uploading, used RAM is 115MB
`ps -o rss= -p #{Process.pid}`.chomp.to_i #=> 115076

# After uploading, used RAM is 159MB
client.video_upload File.open(video_path), title: "test"
`ps -o rss= -p #{Process.pid}`.chomp.to_i #=> 158768
```

**Comment by KieranP** [comment]
I don't know specifically how they manage to achieve it, but we download massive video files (sometimes 5GB in size), and our server doesn't have any major increases in RAM.

A quick look over there code:

The key seems to be using a URL instead of the opened file, which is what we do:
https://github.com/kylejginavan/youtube_it/blob/master/lib/youtube_it/request/video_upload.rb#L79-L80 - Creates a RemoteFile instance

https://github.com/kylejginavan/youtube_it/blob/master/lib/youtube_it/request/remote_file.rb#L8 - The fiber does run until later, but when it does, reads only a chunk of the file at a time

https://github.com/kylejginavan/youtube_it/blob/master/lib/youtube_it/request/video_upload.rb#L724-L737 - Starts generating the request, `data` is the above created RemoteFile object, still nothing in memory at this stage - passed to GreedyChainIO

https://github.com/kylejginavan/youtube_it/blob/master/lib/youtube_it/chain_io.rb#L59 - Setup to read 500kb of the file at a time, then replace that 500kb with another 500kb, still nothing in memory at this point

https://github.com/kylejginavan/youtube_it/blob/master/lib/youtube_it/request/video_upload.rb#L95-L102 - Sends post to youtube. passing in the GreedyChainIO instance. It is only now that the file starts to be read from the URL, and as it does, it also streams that to Youtube, so only 500kb is kept in memory, no file actually downloaded.

It's a very clever way of handling it. Hopefully that made sense.

**Comment by KieranP** [comment]
@claudiofullscreen Looks like YT has come a long way in the past few months which is awesome, but there doesn't seem to have been much progress with this, which is the last thing holding us back from switching (youtube_it works but as you note in your README, the API it uses got deprecated, so we're keen to move on).

We do a lot of uploading to YouTube, and the video files are several GB in size some times and having our background processors bloating several GBs in size because the files are read into memory would obviously be really detrimental. Did you get a chance to read the above explanation of how youtube_it does it? The code in youtube_it is hard to read, but hopefully I explained it well enough above.

**Comment by claudiofullscreen** [comment]
@KieranP I did look it up and it was hard for me to understand as it was for you :cry: 

I will try to address this issue in the upcoming weeks. Of course if you could fork Yt and improve it in any way, that would be a great help!

**Comment by KieranP** [comment]
Hey @claudiofullscreen . I've just gotten around to fixing the memory bloat when uploading video from url. See pull request #120

**Comment by claudiofullscreen** [comment]
Thanks I'll look it up!

**Comment by h0jeZvgoxFepBQ2C** [comment]
Any updates on this?

**Comment by kangkyu** [comment]
Thank you for using yt gem. We recently opened this "Issues" tab back. We are also working on the prioritization process, to maintain yt better. As a part of maintenance plan, we decided to close all issues from the past, because they might be stale and outdated. Please feel free to reopen if you think necessary.
