### ISSUE TITLE
Limit number of returned videos for channel? 

### ISSUE THREAD

**Issue by billyswifty** [claudiob/yt#200]
I can't figure out how to limit the results. 

  channel.videos.where(max_results: 20) doesn't work.

**Comment by billyswifty** [comment]
channel.videos.first(20)

**Comment by illtellyoulater** [comment]
but doesn't this still ask for all the available videos before taking only the first 20?

**Comment by claudiofullscreen** [comment]
No, because a page of results includes 50 videos, so asking for 20 or for 50 is the same: in both cases, only the first page of results is requested (and returned)

**Comment by illtellyoulater** [comment]
Neat. Quick question: is this coming from how YouTube API is designed (letting you ask how many pages you want) with yt just wrapping it, or it is how yt is designed?

**Comment by claudiofullscreen** [comment]
From YouTube, see https://developers.google.com/youtube/v3/docs/videos/list

On Mon, Aug 3, 2015 at 9:49 PM, jjgh notifications@github.com wrote:

> neat, quick question: is this coming from how YouTube API is designed
> (letting you ask how many pages you want) with yt just wrapping it, or it
> is how yt is designed?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Fullscreen/yt/issues/200#issuecomment-127477700.

## 

 Claudio Baccigalupo  | Software Writer  |  Fullscreen, Inc.
http://Fullscreen.net  |  +1.310.202.3333

**Comment by illtellyoulater** [comment]
:+1:  thanks for explaining, it seems a really nice work  overally, I hope I can contribute to it sometime  :)
