### ISSUE TITLE
Creating `Yt::Video` from embed url gets video with wrong parameters

### ISSUE THREAD

**Issue by naz** [claudiob/yt#210]
While initializing a new video from url as such: `https://www.youtube.com/embed/lyodOpUxgHA` it looks like the video data is completely wrong e.g: `"title"=>"embed"`. 
To reproduce it just run this:

``` ruby
Yt::Video.new(url: 'https://www.youtube.com/embed/lyodOpUxgHA').title
```

And it is visible from debug messages that it is trying to do a request to completelly wrong endpoings:

``` bash
curl -X GET -H "content-length: 0" -H "user-agent: Yt::Request (gzip)" "https://www.googleapis.com/youtube/v3/channels?forUsername=embed&key=AIxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx&part=id"
curl -X GET -H "content-length: 0" -H "user-agent: Yt::Request (gzip)" "https://www.googleapis.com/youtube/v3/channels?id=UCaHofiHZt-qSj7yg-pu2pGg&key=AIxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx&part=snippet"
Yt::Errors::NoItems: A request to YouTube API returned no items but some were expected:
{}
```

I know that documentation doesn't specify this type of youtube link as an option for initialization but it could a pretty nice feature to have. Something like this:

``` ruby
video = Yt::Video.new url: 'https://www.youtube.com/embed/lyodOpUxgHA'
```

Thanks for great gem and would be happy to help if needed!

**Comment by claudiofullscreen** [comment]
@Gargol You are right, I didn't consider that format of URL for a YouTube video.

These are the formats that I took into account: 

https://github.com/Fullscreen/yt/blob/master/spec/models/url_spec.rb#L9L20

I should add that too. Thanks!

**Comment by claudiofullscreen** [comment]
@jacknguyen can you take a look? thanks :ribbon:

**Comment by jacknguyen** [comment]
@Gargol just updated to include the embed url format.

**Comment by claudiofullscreen** [comment]
@Gargol Just update to version `0.25.1` (or higher).

**Comment by naz** [comment]
Cool, thanks for such a fast :zap: response!
