### ISSUE TITLE
Where params aren't respected for playlists

### ISSUE THREAD

**Issue by trevorturk** [claudiob/yt#218]
I believe we'd need something along these lines: https://github.com/Fullscreen/yt/blob/master/lib/yt/collections/channels.rb#L24-L28

**Comment by claudiofullscreen** [comment]
Hello! Thanks for stopping by.

Do you have an example of query that you'd like to run?

**Comment by trevorturk** [comment]
Hi @claudiofullscreen, thanks for the reply. I was looking for a way to get the `relatedPlaylists` for a user. I ended up doing this:

``` ruby
    request = Yt::Request.new auth: Yt::Account.new(access_token: token),
      host: "www.googleapis.com",
      path: "/youtube/v3/channels",
      params: { part: "contentDetails", mine: "true" }

    response = request.run
    response.body["items"][0]["contentDetails"]["relatedPlaylists"]
```

...perhaps you could point me to a better way, but I think if we could pass in the `where params` I could avoid using `Yt::Request` here? Sorry, I'm still new to this gem and finding my way around. Thank you!

**Comment by claudiofullscreen** [comment]
I get it now! You want to access playlists like "Liked Videos", is that so?

That's something that I need too… I'll look into that! 

@jacknguyen is this what you were looking at?

**Comment by trevorturk** [comment]
That's right!

A little more background -- the more I've worked with the YouTube API the more strange stuff I find! One thing I ran into was that I can't rely on the `playlists` endpoint to have everything I need. (I'm looking to collect all `Favorites` and `Liked videos` for a user, and I've found that you need to collect different playlists depending on the age of the account.) 

For now I need access to the `playlists` endpoint, which works well with the `yt` gem. However, I also need access to the `contentDetails` for the account's channel to see what playlists are returned, depending on how old the account is. The request I built manually is basically doing what is described here:

https://github.com/Fullscreen/yt/commit/801e03103726e218df13628f46065b7002c70af9#diff-08d70080c6f4ea7936e90e8f5ca7925bR185

...in an old comment from the `yt` gem docs that's talking about the deprecated `youtube_it` gem, explaining how you can request the `relatedPlaylists` for an account's channel.

In any case, I think that being able to pass the params `params: { part: "contentDetails", mine: "true" }` to the channel endpoint would allow me to avoid building the request manually, although perhaps it's worth considering a new method on `account` or `channel` like `account.related_playlists` to make this all easier?

I'd be happy to work up a PR if you like, but I'm just finding my way around the gem and I wasn't sure how you'd like to approach this. If you want to give it a shot, I'm happy to test it out. Otherwise, if you'd like me to work something up, just say the word. 

Thanks again!

**Comment by claudiofullscreen** [comment]
I'm leaning toward your suggestion of `account.related_playlists`. 

Working on it now… I'll keep you updated.
