### ISSUE TITLE
Question regarding accessing YouTube videos marked "private"

### ISSUE THREAD

**Issue by TM818** [claudiob/yt#221]
We have the yt gem (ver 0.25.2) deployed on our Rails 4.2.x project. We have deployed the yt gem on other projects as a replacement for the depreciated YouTubeIt gem and it worked well. 

We are interested in having our YouTube videos set to private so they cannot be viewed unless accessed via our website (where they are embedded in a page). 

Is this possible via the yt gem? If so, what would the process be? We have deployed yt with a YouTube public API key (created via the standard Google Developers console for our YouTube account), but are having issues accessing content YouTube videos marked "private". Do we need to utilize OAuth2 and authorized our own client to access private content?

Please advise as to A) whether or not accessing personal videos set to "private" is possible via the yt gem, and if so, B) what that process is. Thank you.

**Comment by claudiofullscreen** [comment]
It is possible to access private videos (I use `yt` for this in my own projects).

As you suspected, you cannot do so using a public API key. 
In fact, "private videos" are not visible to everyone, but only to the account that owns them.
Therefore, the only way for you to see private video (or to change the privacy status of a video) is to use the credentials of the owner of that video.

Check http://fullscreen.github.io/yt/videos.html for more information!

**Comment by stavro** [comment]
To address TM818's question:

> We are interested in having our YouTube videos set to private so they cannot be viewed unless accessed via our website (where they are embedded in a page).

No, this is not possible.  You cannot embed a private video and allow people to watch it through your website like you are trying to do - regardless of which authentication method you are using.

**Comment by kangkyu** [comment]
Thank you for using yt gem. We recently opened this "Issues" tab back. We are also working on the prioritization process, to maintain yt better. As a part of maintenance plan, we decided to close all issues from the past, because they might be stale and outdated. Please feel free to reopen if you think necessary.
