### ISSUE TITLE
Question: Authenticate without oauth

### ISSUE THREAD

**Issue by davidpdrsn** [claudiob/yt#225]
I'm building a web app that allows users to upload videos. The videos shouldn't go to the users own account, but one that I've made for the app. Ideally the user should not be aware that youtube is storing the videos.

This means that the user can't to through oauth, because they don't know the account that the videos are going to.

Would be great if I could authenticate with the email and password of the shared account. Is doing something like this possible?

**Comment by claudiofullscreen** [comment]
If you have a specific YouTube account that your app is using, then you
should first (on your own) authenticate that account to use the YouTube API
(with all the scopes that you need). At that point, you would get a refresh
token that you can store inside your app. That refresh token would allow
you to do any sort of operation in relation to your YouTube account, such
as uploading videos.

On Wed, Jul 29, 2015 at 5:48 AM, David Pedersen notifications@github.com
wrote:

> I'm building a web app that allows users to upload videos. The videos
> shouldn't go to the users own account, but one that I've made for the app.
> Ideally the user should not be aware that youtube is storing the videos.
> 
> This means that the user can't to through oauth, because they don't know
> the account that the videos are going to.
> 
> Would be great if I could authenticate with an email and password of the
> shared account. Is doing something like this possible?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Fullscreen/yt/issues/225.

## 

 Claudio Baccigalupo  | Software Writer  |  Fullscreen, Inc.
http://Fullscreen.net  |  +1.310.202.3333

**Comment by kangkyu** [comment]
Thank you for using yt gem. We recently opened this "issues" tab back. We are also working on the prioritization process, to maintain yt better. As a part of maintenance plan, we decided to close all issues from the past, because they might be stale and outdated. Please feel free to reopen if you think necessary.
