### ISSUE TITLE
Refresh token is not used with long-running series of requests on behalf of a content owner

### ISSUE THREAD

**Issue by karianne** [claudiob/yt#226]
I am fetching a lot of data out of YT API at once, and it seems to me like there is something wrong with how tokens are refreshed - potentially related to the fact that the requests are made on behalf of a content owner.

I have been able to narrow down my code into the following script:

```
Yt.configure do |config|
   config.api_key = <GOOGLE_API_KEY>
   config.client_id = <GOOGLE_CLIENT_ID>
   config.client_secret = <GOOGLE_CLIENT_SECRET>
   config.log_level = :devel
end

account = Yt::Account.new(refresh_token: <REFRESH_TOKEN>)

account.content_owners.map do |content_owner|
   content_owner.partnered_channels.map do |channel|
     channel.videos.map do |yt_video|
        # This is just to generate some different requests so that the script will run for > 1 hour
        yt_video.category_title
        yt_video.channel_title
        yt_video.views(since: 1.week.ago)[:total]
        yt_video.thumbnail_url(:medium)
        yt_video.view_count
       yt_video.title
     end
   end
end
```

I can see from the yt devel log that the code uses the refresh token to get a new access token when initialized. Then, the code uses that access token to run requests for one hour. When that hour has passed, the Google API (predictably) gives us a 401, which should prompt yt to create yet another access token, using the supplied refresh token. However, the refresh token seems to have disappeared. No attempt is make to use it to create another access token, unless the request log is lying.

After debugging this a bit, it seems to me as we make a new `ContentOwner` object and use this one to authenticate instead of the `account` i created, but the refresh token is not copied to the `ContentOwner` object - meaning that when the access token expires and a new one should be created using the refresh token, it is not there, and because of this 'Authenticatable.authentication' raises.

I might be wrong, though. Please let me know if I am somehow using `yt` wrong, or if this is a legitimate bug.

**Comment by claudiofullscreen** [comment]
Hello, and thanks for stopping by!

> However, the refresh token seems to have disappeared.

Can you help me understand what you mean here? Is `account.refresh_token` suddenly `nil`?

In principle, after an hour, the access token should get refreshed automatically [by the following method](https://github.com/Fullscreen/yt/blob/master/lib/yt/associations/has_authentication.rb#L55-L61):

``` ruby
# Obtains a new access token.
# Returns true if the new access token is different from the previous one
def refreshed_access_token?
  old_access_token = authentication.access_token
  @authentication = @access_token = @refreshed_authentications = nil
  old_access_token != authentication.access_token
end
```

You could try adding a `debugger` there and see if it stops… or what happens exactly.
If you don't want to wait for an hour, just make some requests, then manually set the `access_token` to `nil`, and Yt should try to get a new access token for you.

**Comment by karianne** [comment]
> Can you help me understand what you mean here? Is account.refresh_token suddenly nil?

Yes and no. The public method `refresh_token` on `Authenticatable` delegates to `authentication`. `@authentication` is set to `nil` in the method you pasted. The `authentication` method, however, uses the `@refresh_token` variable, and that variable is set to nil. 

I did some more debugging, and it looks like the `ContentOwner` object is initialised with the parameter `authentication: <account authentication>`. This, however, does not set the `@refresh_token` variable - which causes refresh to fail when the access token expires.

**Comment by claudiofullscreen** [comment]
If I understand correctly, what you are experiencing is that the `refresh_token` never gets set in the `ContentOwner`. Only the `access_token` gets set, therefore your requests are fine for the first hour, but then stop working (because the token cannot be refreshed).

Is that what you see?

**Comment by karianne** [comment]
As far as I understand, the `access_token` is fetched from the `authentication` object when it is added to the headers in `Request#run`. So that `@access_token` is not set in `Authenticatable`does actually not affect anything. When the `refresh_token` needs to be used to get a new access token, however, that causes the problem.

**Comment by karianne** [comment]
I made a PR with a fix.

**Comment by kangkyu** [comment]
Thank you for using yt gem. We recently opened this "issues" tab back. We are also working on the prioritization process, to maintain yt better. As a part of maintenance plan, we decided to close all issues from the past, because they might be stale and outdated. Please feel free to reopen if you think necessary.
