### ISSUE TITLE
A request to YouTube API was sent without a valid authentication

### ISSUE THREAD

**Issue by uzomao** [claudiob/yt#230]
I am getting this error when I try to upload to YouTube from my rails app. What's strange is that the uploads work the first two or three times when there is no existing video in the database and then I get this error for subsequent uploads. I have an `upload!` method in my `video_upload` model which handles the actual uploading of the video: 

```
def upload!(user)
    account = Yt::Account.new access_token: user.token
    account.upload_video self.file, title: self.title, description: self.description
  end
```

I am led, from the error logs, to believe that the problem is coming from an inauthentic access token but I am not sure if this is the case / why. The access token I have for my API calls should work fine.

Here is part of the error I am getting:

```
A request to YouTube API was sent without a valid authentication: {"error"=>{"errors"=>[{"domain"=>"global", "reason"=>"authError", "message"=>"Invalid Credentials", "locationType"=>"header", "location"=>"Authorization"}]
```

Any help would be appreciated. Thanks.

**Comment by claudiofullscreen** [comment]
Hello @chidumaga !
By default, an access token provided by YouTube will last for 30 minutes.
After that time, you will need to refresh that token.

Might that be the problem? Does the error occur after ~ 30 minutes?

**Comment by uzomao** [comment]
Thanks for your response @claudiofullscreen. That may very well be the problem; I'll check to make sure now.

It's weird though because I only started getting that error yesterday after about a week of uploading videos to YouTube through the app...could there be a reason for this?

**Comment by bodrovis** [comment]
@chidumaga as per this http://community.sitepoint.com/t/youtube-api-version-3-on-rails/112176/16
Have you managed to find a cause? :)

**Comment by uzomao** [comment]
Sorry @bodrovis , should have updated this much earlier. It's exactly as @claudiofullscreen suggested, my access token is expiring after a set period of time, presumably 30 minutes. With a refresh token the problem should be solved.

**Comment by bodrovis** [comment]
@chidumaga great :)
