### ISSUE TITLE
Failing collections spec on master

### ISSUE THREAD

**Issue by ToadJamb** [claudiob/yt#231]
When I run the test suite locally (excluding request specs), I get the following failure:

Yt::Collections::Reports#within given the request raises error 400 with "Invalid Query" message but returns a success code 2XX the second time should not fail
     Failure/Error: let(:result) { reports.within Range.new(5.days.ago, 4.days.ago), nil, nil, :day, nil }
     NoMethodError:
       undefined method `transform_values' for {:total=>20}:Hash
     # ./lib/yt/collections/reports.rb:73:in`block (2 levels) in within'
     # ./lib/yt/collections/reports.rb:72:in `each'
     # ./lib/yt/collections/reports.rb:72:in`map'
     # ./lib/yt/collections/reports.rb:72:in `block in within'
     # ./lib/yt/actions/list.rb:9:in`each'
     # ./lib/yt/actions/list.rb:9:in `flat_map'
     # ./lib/yt/actions/list.rb:9:in`flat_map'
     # ./lib/yt/collections/reports.rb:71:in `within'
     # ./lib/yt/collections/reports.rb:100:in`rescue in within'
     # ./lib/yt/collections/reports.rb:61:in `within'
     # ./spec/collections/reports_spec.rb:12:in`block (3 levels) in <top (required)>'
     # ./spec/collections/reports_spec.rb:26:in `block (6 levels) in <top (required)>'
     # ./spec/support/fail_matcher.rb:5:in`call'
     # ./spec/support/fail_matcher.rb:5:in `block (2 levels) in <top (required)>'
     # ./spec/collections/reports_spec.rb:26:in`block (5 levels) in <top (required)>'

**Comment by claudiofullscreen** [comment]
What version of Ruby and ActiveSupport are you using? Thanks!

**Comment by ToadJamb** [comment]
This is my `Gemfile.lock`:

```
PATH
  remote: .
  specs:
    yt (0.25.4)
      activesupport

GEM
  remote: https://rubygems.org/
  specs:
    activesupport (4.1.4)
      i18n (~> 0.6, >= 0.6.9)
      json (~> 1.7, >= 1.7.7)
      minitest (~> 5.1)
      thread_safe (~> 0.1)
      tzinfo (~> 1.1)
    coveralls (0.7.0)
      multi_json (~> 1.3)
      rest-client
      simplecov (>= 0.7)
      term-ansicolor
      thor
    diff-lcs (1.2.5)
    docile (1.1.5)
    i18n (0.6.11)
    json (1.8.1)
    mime-types (2.3)
    minitest (5.4.3)
    multi_json (1.10.1)
    netrc (0.7.7)
    rake (10.4.2)
    rest-client (1.7.2)
      mime-types (>= 1.16, < 3.0)
      netrc (~> 0.7)
    rspec (3.0.0)
      rspec-core (~> 3.0.0)
      rspec-expectations (~> 3.0.0)
      rspec-mocks (~> 3.0.0)
    rspec-core (3.0.3)
      rspec-support (~> 3.0.0)
    rspec-expectations (3.0.3)
      diff-lcs (>= 1.2.0, < 2.0)
      rspec-support (~> 3.0.0)
    rspec-mocks (3.0.3)
      rspec-support (~> 3.0.0)
    rspec-support (3.0.3)
    simplecov (0.9.0)
      docile (~> 1.1.0)
      multi_json
      simplecov-html (~> 0.8.0)
    simplecov-html (0.8.0)
    term-ansicolor (1.3.0)
      tins (~> 1.0)
    thor (0.19.1)
    thread_safe (0.3.4)
    tins (1.3.0)
    tzinfo (1.2.1)
      thread_safe (~> 0.1)
    yard (0.8.7.4)

PLATFORMS
  ruby

DEPENDENCIES
  bundler
  coveralls
  rake
  rspec
  yard
  yt!

BUNDLED WITH
   1.10.5
```

**Comment by kangkyu** [comment]
Thank you for using yt gem. We recently opened this "issues" tab back. We are also working on the prioritization process, to maintain yt better. As a part of maintenance plan, we decided to close all issues from the past, because they might be stale and outdated. Please feel free to reopen if you think necessary.
