### ISSUE TITLE
Search playlist

### ISSUE THREAD

**Issue by jocelyndrean** [claudiob/yt#245]
Hello everyone,
Thank you for this gem. I try to search playlists by name, but doesn't seems to work. Normally the URL should look like that : https://www.googleapis.com/youtube/v3/search?part=snippet&maxResults=1&q=Top+Tracks+-+Radiohead&type=playlist&key={YOUR_API_KEY}

Do you know if this is possible to search playlist with this gem or if I have to code it and then PR ?

Thank you for your feedback.
Jocelyn

**Comment by kangkyu** [comment]
Thank you for using yt gem. We recently opened this "issues" tab back. We are also working on the prioritization process, to maintain yt better. Unfortunately we decided to close all issues from the past as a part of maintenance plan. Please feel free to reopen if you think necessary.
