### ISSUE TITLE
video.reports only: [:viewer_percentage] doesn't work. Deprecated?

### ISSUE THREAD

**Issue by hildevestol** [claudiob/yt#248]
https://github.com/Fullscreen/yt/blob/master/lib/yt/models/video.rb#L393
`video.reports only: [:viewer_percentage]` doesn't work.. seems like it's deprecated by YouTube?

> viewerPercentage (core metric)
> The percentage of viewers who were logged in when watching the video or playlist. This is a core metric and is subject to the Deprecation Policy.
> https://developers.google.com/youtube/analytics/v1/dimsmets/mets

**Comment by kangkyu** [comment]
Something like `dimensions=gender` should be added to the request.
