### ISSUE TITLE
Timeout for requests

### ISSUE THREAD

**Issue by slhck** [claudiob/yt#360]
We're facing issues with a web app running the `yt` Gem when requests run into 403 errors due to the quota being exceeded. These requests also take a long time before they return – usually five seconds or more – while regular requests to, e.g., a video's `title` take a fraction of a second. That brings down the overall performance of the app.

Is there any way to have `yt` requests time out when they reach a given time limit so that such failures can be caught early on?

I see that, in principle, the `net/http` options could be added [here](https://github.com/Fullscreen/yt/blob/master/lib/yt/request.rb#L111) or maybe [here](https://github.com/Fullscreen/yt/blob/master/lib/yt/request.rb#L175)?

These options would be:

- `open_timeout`
- `read_timeout`
- `write_timeout`

But I don't see how they could be specified in a user-friendly manner…

(I am aware this seems like an XY problem. It partly is. However, seeing that other libraries that perform requests provide some timeout options, I thought it wouldn't hurt to ask.)

**Comment by kangkyu** [comment]
> These requests also take a long time before they return

I think it takes long because yt retries a few times
https://github.com/Fullscreen/yt/blob/master/lib/yt/request.rb#L201

**Comment by slhck** [comment]
Ah, that's good to know. In my case though, the *daily* quota is sometimes exceeded, so the request fails with a 403, and it's *not* worth retrying it. In fact, I guess that retrying it exacerbates the problem. Does this hint at some underlying issue (i.e., checking daily vs. minutely quota)?

**Comment by kangkyu** [comment]
I think you're suggesting a feature to separate daily limit error from other quota limit errors, and request only once (no retry) for the daily limit error. Thank you for suggestion. But for now I don't think we are planning to add that. Feel free to open a pull request, we can discuss further.

**Comment by slhck** [comment]
Well, that's not what I originally suggested, but I understand now what the underlying problem is. I think it's not worth investing a lot of time since you can't really figure out what the quota limit is on the client side.
