### ISSUE TITLE
Comment Functionality

### ISSUE THREAD

**Issue by tvanzo** [claudiob/yt#361]
I am looking for a tool to help me retrieve all comments with particular search terms from a particular Youtube Channel.  The Youtube api allows this, but it seems this gem doesn't include this functionality? And I am not an experienced programmer to know how to do it without a client like yt ;P. Any thoughts?
Thanks!

https://developers.google.com/youtube/v3/docs/commentThreads/list?apix_params=%7B%22part%22%3A%22id%2C%20replies%2C%20snippet%22%2C%22allThreadsRelatedToChannelId%22%3A%22UC8Ykci4MKSSdTJYuYp53G7A%22%2C%22maxResults%22%3A100%2C%22order%22%3A%22time%22%7D

**Comment by blerg-rush** [comment]
The gem does indeed retrieve comments! I can try to help you write a call if you tell me which comments and what information from them you'd like retrieved, but as an example, the following code will gather a list of comment threads from [this example video](https://www.youtube.com/watch?v=EBIsZlV1jHk), which you could then iterate through to call [these methods](https://github.com/Fullscreen/yt/blob/master/lib/yt/models/comment_thread.rb):

```ruby
yt_video = Yt::Video.new id: 'EBIsZlV1jHk'
yt_top_level_comments = yt_video.comment_threads
```

**Comment by dgb** [comment]
That looks about right. Thanks for helping out @TheWillGabriel !

For further info check out the docs:

https://www.rubydoc.info/gems/yt/0.32.3/Yt/Models/Video#comments-instance_method
https://www.rubydoc.info/gems/yt/0.32.3/Yt/Models/Comment
