### ISSUE TITLE
'Hello World' video no longer exists

### ISSUE THREAD

**Issue by blerg-rush** [claudiob/yt#362]
The [video](https://www.youtube.com/watch?v=BPNYv0vd78A) referenced in the [yt installation instructions](https://fullscreen.github.io/yt/index.html) no longer exists, leading the command `yt info` to fail its YouTube API request.

[Line 11 of bin/yt](https://github.com/Fullscreen/yt/blob/master/bin/yt#L11) will need a new working video ID.

**Comment by kangkyu** [comment]
This is now fixed on current version
```sh
$ gem update yt
Updating installed gems
Updating yt
Fetching: yt-0.32.5.gem (100%)
Successfully installed yt-0.32.5
Gems updated: yt
$ yt info
Yt version 0.32.5
YouTube on the tube!
```
