### ISSUE TITLE
Questions about handling expired tokens

### ISSUE THREAD

**Issue by soundnotation** [claudiob/yt#371]
I don't know whether this should be written as an issue here or elsewhere - apologize if this is not the right place.

Anyway, I'm trying out your gem and our app will eventually fall in the case described [here](https://github.com/Fullscreen/yt#web-apps-that-require-user-interactions).
I'm also pretty new to OAuth, so I wanted to ask something that's not written in the docs, nor in the web (or at least I can't figure out, or I'm either missing some knowledge of):

I set up `client_id`, `client_secret` and `api_key` for my app.
Suppose I save both access and refresh tokens for an account (obtained after the first authorization) to my db.

0. Is it sensible to save both or just e.g. the refresh token?

1. I try `account = Yt::Account.new access_token:  'ya29.ZAF6McAOf0OwU'`.
How can one manage the case when an **access** token is expired? I.e.:

    1.1. Is a `rescue` necessary here? If yes, should I rescue from `Yt::Errors::RequestError` or `Yt::Errors::Unauthorized`?

2. You say
    > If you don’t have the account’s access token, but you have the refresh token

    Do you mean that `account.access_token` is `nil`, or just expired/invalid?
    In case `nil`, when can this occur?

3. I try `account = Yt::Account.new refresh_token: '1/ddxHq4ph-BdR954Xh'`.
Same questions as 1., but for a **refresh** token?

4. I know access tokens last around 1 hour. But can you manually set tokens' expiration dates for an account? If not, how can I replicate the token expired cases in the console, without waiting for the tokens to expire, in order to test them?

Thanks for your patience, even if you find my questions silly.

**Comment by kangkyu** [comment]
> 1. I try `account = Yt::Account.new access_token:  'ya29.ZAF6McAOf0OwU'`.
>    How can one manage the case when an **access** token is expired? I.e.:
>    1.1. Is a `rescue` necessary here? If yes, should I rescue from `Yt::Errors::RequestError` or `Yt::Errors::Unauthorized`?

I think you can rescue `Yt::Errors::Forbidden` in your case.

> 2. You say
>    > If you don't have the account's access token, but you have the refresh token
>
>    Do you mean that `account.access_token` is `nil`, or just expired/invalid?
>    In case `nil`, when can this occur?

I haven't seen the case YouTube returns nil value for access token. That simply means "if you don't have a valid access_token to authenticate"

> 3. I try `account = Yt::Account.new refresh_token: '1/ddxHq4ph-BdR954Xh'`.
>    Same questions as 1., but for a **refresh** token?

If you're asking `refresh_token` is expired, that probably means the user has revoked access to your application and you need to ask them to auth again.

> 4. I know access tokens last around 1 hour. But can you manually set tokens' expiration dates for an account? If not, how can I replicate the token expired cases in the console, without waiting for the tokens to expire, in order to test them?
>

I don't think the `expire_at` or `expire_in` can be changed from user's side. Yes, you can refresh it any time.
