### ISSUE TITLE
Querying deleted videos returns Yt::Errors::NoItems

### ISSUE THREAD

**Issue by adesurirey** [claudiob/yt#382]
When initializing deleted videos, any method returns the following error:
```
Yt::Errors::NoItems: A request to YouTube API returned no items but some were expected
```

Example with this video: https://www.youtube.com/watch?v=HQMJ88nQ1GA
```
[1] pry(main)> video = Yt::Video.new(id: "HQMJ88nQ1GA")
=> #<Yt::Models::Video:0x00007fe1dd357250 @auth=nil, @id="HQMJ88nQ1GA">
[2] pry(main)> video.deleted?
Yt::Errors::NoItems: A request to YouTube API returned no items but some were expected:
To display more verbose errors, change the configuration of Yt with:

Yt.configure do |config|
  config.log_level = :debug
end
```

**Comment by kangkyu** [comment]
When I checked just now YouTube returns empty response on `/videos?id=HQMJ88nQ1GA` https://developers.google.com/youtube/v3/docs/videos/list (you can try with "Try This API")

I don't know why YouTube shows this behavior, but `yt` returns `Yt::Errors::NoItems` when there's empty response from YouTube.
