### ISSUE TITLE
Do we really need ActiveSupport gem in dependencies?

### ISSUE THREAD

**Issue by k0va1** [claudiob/yt#386]
I think it's not a good idea to put all activesupport stuff inside gem. Monkeypatching is shit

**Comment by dgb** [comment]
I'd love to remove ActiveSupport and make it an optional dependency (it's on our todo list here https://github.com/Fullscreen/yt/issues/351#issue-458146093). We are using it though, for both the monkeypatching stuff and instrumentation.
