### ISSUE TITLE
Limit pagination in YT gem

### ISSUE THREAD

**Issue by rimshaxoho** [claudiob/yt#389]
I am using 

```
videos = Yt::Collections::Videos.new
videos.where(q: 'star war', safe_search: 'none')
```

but i can't find any variable to limit pagination like my search has 500+ videos and i just want first 100. 

```
videos.where(q: 'star war', safe_search: 'none', max_results: 10)
```
it will just limit the per page request. Can you please update documentation if there is any way.

**Comment by kangkyu** [comment]
Hello

```
videos = Yt::Collections::Videos.new
videos.where(q: 'star war', safe_search: 'none').first(10)
```
This will only make 1 request. Is that what you need? About documentation, we should work on it. Thank you

**Comment by rimshaxoho** [comment]
> Hello
> 
> ```
> videos = Yt::Collections::Videos.new
> videos.where(q: 'star war', safe_search: 'none').first(10)
> ```
> 
> This will only make 1 request. Is that what you need? About documentation, we should work on it. Thank you

Yes exactly I was looking for that and found help in closed issues. But I think it will be great if you put this in documentation.
Thank You!!!
