### ISSUE TITLE
channel.videos.where(max_results: 2) generates 2 queries

### ISSUE THREAD

**Issue by Paprikas** [claudiob/yt#391]
Found it with VCR gem.
The difference is that the second query has `pageToken=<TOKEN>` parameter and there is different videos (i guess because of sorting)

**Comment by dgb** [comment]
Can you point out a case in which this is happening? I think it could be something related to sorting and/or the way Yt tries to workaround the search endpoint's 500 video limit (see https://github.com/Fullscreen/yt/issues/363 for more info).

**Comment by Paprikas** [comment]
Hi @dgb 
I think it depends on how many videos channel contains. With one video - only one request sent.
Tested on channel with 59 videos - two requests.

**Comment by kangkyu** [comment]
Probably because Yt fetches 50 videos at a time to get metadata after searching the first 50 videos. If you have further concerns let us know
