### ISSUE TITLE
Why some videos are not there in the channel.videos association

### ISSUE THREAD

**Issue by amitamb** [claudiob/yt#405]
I am trying to fetch videos associated with a channel but some videos are missing from the list.

Is that expected? Are there some filters being applied here?

Can I see some log of requests being made by the gem?

**Comment by kangkyu** [comment]
you can check logs by setting log level as one of env variables. See
https://github.com/Fullscreen/yt/blob/master/lib/yt/models/configuration.rb#L54
https://github.com/Fullscreen/yt#configuring-with-environment-variables

**Comment by kangkyu** [comment]
Actually all the videos of channel is not expected by video search, you have workaround to get playlist id of "Play All" and then get all the videos of that playlist
