### ISSUE TITLE
Captions API

### ISSUE THREAD

**Issue by fw42** [claudiob/yt#413]
Using this gem, is there a way to download a video's [captions](https://developers.google.com/youtube/v3/docs/captions)? If not, would be awesome if you could add that feature. Thanks!

**Comment by fw42** [comment]
Just saw that it was implemented in https://github.com/Fullscreen/yt/pull/332 but never shipped 😢

**Comment by kangkyu** [comment]
@fw42 are you still interested in this feature?

**Comment by fw42** [comment]
I'm personally not using this project at the moment, so if I'm the only person that was interested in this feature, it might not be worth the effort. I still think it would be useful in general though. Thanks for asking!
