### ISSUE TITLE
Project status

### ISSUE THREAD

**Issue by deanpcmad** [claudiob/yt#415]
Hey, I've been trying to get in contact with the owner of both this repo and Rubygem as I would be interested in taking over the project. My email address should be on my project if you want to chat about this 😄

**Comment by kangkyu** [comment]
@deanpcmad did you contact Warnermedia?

**Comment by deanpcmad** [comment]
I'm not sure who to get in contact with 😕  I was told by the last person who commited that @binarygeek might be able to help?

**Comment by jaredcwhite** [comment]
It would be awesome if this repo/gem could continue to get maintained! I only just started using it on a project, and I feel like the ergonomics are truly great. A very nicely Ruby-like API gem. 👏🏻

**Comment by justinhoward** [comment]
A little update here. There are a few folks putting in some time to preserve this and other open-source Fullscreen projects. Before we bring in any outside maintainers, we're looking for people who have long-term experience with these projects. I'll keep this thread updated on progress. The plan is ultimately to revive yt and get it ready to accept OSS contributions.

**Comment by deanpcmad** [comment]
That sounds promising. I've been using the gem in a project of mine for over a year.

**Comment by AlexWayfer** [comment]
With recent major changes in official Google gems I'm pretty interested in this project.

**Comment by deanpcmad** [comment]
I'm still happy to take over the project

**Comment by kangkyu** [comment]
I became one of maintainers here. I am not the original developer, but I have experience with Yt for 5 years during my time at Fullscreen.

**Comment by justinhoward** [comment]
Awesome @kangkyu. Thanks for picking it back up! @deanpcmad, feel free to open some issues or PRs if you'd like to help out with the project!
