### ISSUE TITLE
Documentation page is down

### ISSUE THREAD

**Issue by sunwooz** [claudiob/yt#416]
You can still find the docs on WayBackMachine here - https://web.archive.org/web/20201214232812/https://fullscreen.github.io/yt/videos.html

**Comment by justinallenmarsh** [comment]
How can we get the documentation back up?

**Comment by kangkyu** [comment]
I think we can make nullscreen.github.io and then apply the doc. It's a branch in this repo

**Comment by justinhoward** [comment]
It looks like the docs site is available, but it's moved URLs after the org change https://nullscreen.github.io/yt/videos.html. A PR to update the links would be much appreciated.
