### ISSUE TITLE
Pagination for Playlist items

### ISSUE THREAD

**Issue by simaofreitas** [claudiob/yt#424]
Hi!

I'm trying to get all videos from a playlist
When I do:
```
x = Yt::Playlist.new id: <some id>
x.playlist_items.size
=> 612
```
I get the actual number. ex: 612

But iterating over the results I only get 50.

How do I get paginate the results and look at all of them? Any way to access the "nextPageToken"?

Thanks

**Comment by kangkyu** [comment]
Hello @simaofreitas you can use pagination token from the previous response when request next page. See https://github.com/nullscreen/yt/blob/master/lib/yt/actions/list.rb#L95

**Comment by simaofreitas** [comment]
Hey @kangkyu thanks for your response.
But I can't get to that value. I'm sure I'm doing some wrong but can you help?

```
p = Yt::Playlist.new id: 'UU7o6_9PaatOjXSjN7kCdsww'
p.playlist_items.first => returns the first item
p.playlist_items.last_response => No Method Error
```
How do I get to the list object?

Thanks

**Comment by kangkyu** [comment]
You can get "nextPageToken" in this way

```
p = Yt::Playlist.new id: 'UU7o6_9PaatOjXSjN7kCdsww'
p.playlist_items.first
p.playlist_items.instance_variable_get("@last_response").body['nextPageToken']
```

And the list object is returned when you call `p.playlist_items`.

**Comment by kangkyu** [comment]
> look at all of them

ah, you can `count` before you run anything.
```rb
p = Yt::Playlist.new id: 'UU7o6_9PaatOjXSjN7kCdsww'
p.playlist_items.count
```

**Comment by simaofreitas** [comment]
thanks!
